### ISSUE TITLE
Getting reports filtered by date range

### ISSUE THREAD

**Issue by felipeferri** [mautic/api-library#106]
I am using the Mautic REST api using Python Requests.

I am using the following HTTP command to get a specific report:

GET http://myserver/api/reports/report_id

When I do this I receive a json with the last 30 days worth of leads present in the report. I didn't find anywhere documentation on the parameters for the reports endpoint. Which parameters can I use to set the number of leads to return and the range of lead register dates?

Thank you.

**Comment by funkizer** [comment]
Nothing in 9 months? I need the same information, please. The `api/reports/:id` -endpoint is still not mentioned anywhere in the docs: https://developer.mautic.org/#rest-api

**Comment by henriquekfmaia** [comment]
I have the same problem
Does anyone know if it is possible to request this information with a date range filter?

**Comment by escopecz** [comment]
When I [look into the code](https://github.com/mautic/mautic/blob/staging/app/bundles/ReportBundle/Controller/Api/ReportApiController.php#L77) I can see what query params can be used:

- dateFrom
- dateTo
- page
- limit

Can some of you please update the docs for future generations?

Oh, wait. I can see the report documented on git:

https://github.com/mautic/developer-documentation/blob/master/source/includes/_api_endpoint_reports.md#response

But it's missing in https://developer.mautic.org/#rest-api

It probably must be just added into https://raw.githubusercontent.com/mautic/developer-documentation/master/source/index.md

I'll try that.

**Comment by escopecz** [comment]
There you go: https://developer.mautic.org/#get-report
