### ISSUE TITLE
Getting error  Invalid grant_type parameter or parameter missing

### ISSUE THREAD

**Issue by bounmed** [mautic/api-library#109]
hi,

I have installed mautic in my server and trying to connect it with my website i installed api-library and API Tester  but when i send the request i get this error.

Incorrect access token parameters returned: Invalid grant_type parameter or parameter missing

**Comment by escopecz** [comment]
Can you share your auth code?

**Comment by bounmed** [comment]
Is it safe to share it here ? i can send it by email.

**Comment by escopecz** [comment]
I think that it's safe to share one method from your code. It shouldn't be that different from the [sample code](https://github.com/mautic/api-library#authorization) anyway. I'd prefer more if you could double-check your code and compare it with the docs to find the problem, but I thought you write here as your last resort.

**Comment by bounmed** [comment]
I didn't create anycode yet i just tried the [apitester](https://github.com/mautic/api-library/tree/master/apitester) with my mautic instace and i get that error from the apitester not my code.

**Comment by escopecz** [comment]
Ok, then there must be some problem with how you configured the API Tester or how you created the Oauth tokens. Can you write step by step list of what you did?

**Comment by bounmed** [comment]
Thank you John,
Well i have vps server using Debian 8.4, PHP 5.6.30, apache Apache/2.4.10, Mysql mysql  Ver 14.14 Distrib 5.5.54

I installed the latest released version of Mautic, installed it than i enabled API from 
Configuration -> API Settings
form API Credentials  i created two clients one for OAuth1 and the other for OAuth2 stating the redirect URI (the link of the api-library tester url)  and the name.

Than i installed the  api-library in another domain, i opened the apitester link in the browser and entered Mautic url,  Client Key and Client Secret i got from Mautic and clicked Authorize button .

when i click the Authorize it asks me to connect when i enter the login and password than it return to apitester url with that error:

`Incorrect access token parameters returned: Invalid grant_type parameter or parameter missing`

I tried both OAuth1 and OAuth2.
The server date is correct.
Mautic is working good.

**Comment by escopecz** [comment]
From [what Google found](https://www.google.com/search?q=oauth+Invalid+grant_type+parameter+or+parameter+missing&rlz=1C5CHFA_enCZ727CZ727&oq=oauth+Invalid+grant_type+parameter+or+parameter+missing&aqs=chrome..69i57.1909j0j7&sourceid=chrome&ie=UTF-8), it could be an issue in the redirect URL.

**Comment by bounmed** [comment]
Thank you John,
I installed nginx on the same server on another port and don't get the error.
It's working very good now using nginx so i think the problem is with apache.

**Comment by escopecz** [comment]
I'm using Apache2 successfully. I'll close this issue since it seem it's a server config issue. Thanks for getting back to us!
