### ISSUE TITLE
API Endpoint GET /segments returns too few elements

### ISSUE THREAD

**Issue by derXear** [mautic/api-library#113]
Hey there!

I have found that the `GET /segments` endpoint is just returning 30 entries, but there are definitely more segments in our Mautic instance. Is this an issue or do I miss something? Can someone verify this please?

Thank you!

**Comment by escopecz** [comment]
I noticed that the developer docs for segments are missing this table, but it's the same as for any other entity. Look for example here: https://developer.mautic.org/#list-assets

`start` and `limit` are second ant third param if you use the API library. If not, just use those as the query params with the values you need.

**Comment by romainlaisne** [comment]
You should reopen this one, the doc is still not complete. thanks
