### ISSUE TITLE
Printing error instead of logging it

### ISSUE THREAD

**Issue by r-martins** [mautic/api-library#115]
at vendor/mautic/api-library/lib/Api/Api.php:299 you have a var_export that always outputs the error array, causing the common error "headers already sent".

`$this->getLogger()->error('Mautic API returned errors: '.var_export($response['errors']));`

You can just avoid it by passing _true_ as second parameter to var_export call.

Thank you and congratulations for this amazing library.
I'm using it to integrate with Magento, and soon will put the module available at github too.

**Comment by escopecz** [comment]
Try to upgrade to the latest version. It's been fixed a while back.

**Comment by r-martins** [comment]
I'm already using 2.6.0 and still like [this](https://github.com/mautic/api-library/blob/ea49a7e50cce3b59f85f2794c366c44e622e80f1/lib/Api/Api.php#L299)

**Comment by escopecz** [comment]
It's [fixed](https://github.com/mautic/api-library/blob/master/lib/Api/Api.php#L299) in the latest code. I'll try to release 2.9.0 tag today, but use master branch as a quick fix until 2.9.0 will be released.
