### ISSUE TITLE
Add Tag to contact

### ISSUE THREAD

**Issue by dgram** [mautic/api-library#116]
Hi,

is it possible to add tags to contacts?
I have 2 use cases, define tag on contact creation, and add tag to existing contact.

regards

**Comment by escopecz** [comment]
Sure, there is an example in the tests: https://github.com/mautic/api-library/blob/master/tests/Api/ContactsTest.php#L31-L34

**Comment by dgram** [comment]
thx, but can it be, that we have to configure them to show them by the library? i use the zapier integration, i want to use webhook to mautic, and i dont get the "tags" field to set the field value.

is this an integration problem or an configuration problem?
and to use the api directly its do slow do add new entry and filter them by email before (about 1.2 seconds)

regards

**Comment by escopecz** [comment]
I don't understand now. Are we talking about webhooks or API.

**Comment by dgram** [comment]
sorry, the workflow looks something like this:

1.) our site makes an webhook call to zapier with given data
2.) we create an "zap" where the webhook data will be passed to mautic create/update contact
3.) but on the zap its not possible to connect the given tags from the webhook with an mautic field

do we need to configure mautic (additional fields) or something else?

regards

**Comment by escopecz** [comment]
I'm not sure how your Zap is configured, but could you test https://github.com/mautic/mautic/issues/2838#issuecomment-309875567?

**Comment by escopecz** [comment]
@ryancwalsh You didn't say that you've tried it and it did not work. You can use the same format for creating or updating contacts and tags. So far I don't know about any issue here.
