### ISSUE TITLE
Create new REST API failed

### ISSUE THREAD

**Issue by arunkumarrmrj** [mautic/api-library#121]
I've use basic Auth method to create new contact

I got a Response for 

`{
    "error": {
        "code": 403,
        "message": "Sorry, to prevent spam, this feature is not enabled for free accounts. You can email support@mautic.com to answer a few questions and request we enable it for you."
    }
}`

**Comment by escopecz** [comment]
Actually, the error message is self-explanatory. You'll have to either upgrade to a paid plan or if you have questions, send them to the email address provided in the email message.

**Comment by tuliobbs** [comment]
I have sent them an e-mail. When they answer me I will post here the result.

Anybody already got the answer?

**Comment by tuliobbs** [comment]
They actually reply :)

I am not seeing that error anymore, but the leads also do not go to my lead list..... Let's see what they say about that.
