### ISSUE TITLE
Create new contact

### ISSUE THREAD

**Issue by arunkumarrmrj** [mautic/api-library#122]
Which parameters are used to create a new contact

Any one have a example in http,curl methods.

**Comment by escopecz** [comment]
When I'm looking for a working example, I look at the tests folder:

https://github.com/mautic/api-library/blob/master/tests/Api/ContactsTest.php#L26

**Comment by arunkumarrmrj** [comment]
This Test folder is a PHP

But I'm a coldfusion developer ,I don't know PHP so could you please any common language for curl use
for contact new endpoint

**Comment by escopecz** [comment]
I thought you ask about this PHP library since this is issue for the PHP library. Maybe ask at Mautic next time. The part of it is at https://developer.mautic.org/?php#create-contact.

Encode the attributes you want to save into the URL query.
`POST /contacts/new?firstname=John&lastname=Doe`

**Comment by diegodorgam** [comment]
still doesn't work for me, tried a lot issues, documentation (which is not pretty clear by the way) before finding this issue. 
I'm using POSTMAN by now, in the end I'll probably be using a python script for this, so as our friend above, I won't be using php, so I'm trying to guess how to input a new contact.
What I first noticed is that the endpoint is actually `POST /api/contacts/new` right? I've tried `/contact/new` and it returns a HTML file instead a API response. 
So for now, when I call the endpoint like this:
```shell
 curl -X POST 'https://m.mydomain.org.br/api/contacts/new?firstname=Diego&lastname=Dorgam&email=suporte@dorgam.com.br' \
  -H 'Authorization: Basic ZG9yZ2FtOjUwQEFndFlsZXJhSTJrMTk='
```
It returns me a JSON object with null field values:
```json
{
    "contact": {
        "isPublished": true,
        "dateAdded": "2019-02-11T20:01:25-02:00",
        "dateModified": null,
        "createdBy": 2,
        "createdByUser": "Diego Dorgam",
        "modifiedBy": null,
        "modifiedByUser": null,
        "id": 36521,
        "points": 0,
        "color": null,
        "fields": {
            "core": {
                "firstname": {
                    "id": 2,
                    "group": "core",
                    "label": "First Name",
                    "alias": "firstname",
                    "type": "text",
                    "value": null
                },
                "lastname": {
                    "id": 3,
                    "group": "core",
                    "label": "Last Name",
                    "alias": "lastname",
                    "type": "text",
                    "value": null
                },
                "email": {
                    "id": 6,
                    "group": "core",
                    "label": "Email",
                    "alias": "email",
                    "type": "email",
                    "value": null
                },
                ...
        },
        "lastActive": null,
        "owner": null,
        "ipAddresses": [],
        "tags": [],
        "utmtags": null,
        "stage": null,
        "dateIdentified": null,
        "preferredProfileImage": null,
        "doNotContact": [],
        "frequencyRules": []
    }
}
```
And when I check in mautic, it is creating contacts like this:
<img width="1050" alt="captura de tela 2019-02-11 as 20 14 32" src="https://user-images.githubusercontent.com/12052193/52597304-bec36200-2e39-11e9-8215-ab600fef140b.png">

I've already bumped to the cache clearing problem, so it's not it. I've also already tried to send a json payload with the fields as it comes in the response, which obviously didn't work either.

So, any hints are welcome, 
thanks in advance.

**Comment by escopecz** [comment]
You are sending POST, but the data are in URL query. You have to actually use the POST body.

It'd be great if you could improve the docs so it will be clearer: https://github.com/mautic/developer-documentation

**Comment by igmarinelli** [comment]
Hi, you need to send the data as raw json , here's the example of the request: 

```
def create_contact_mautic(email, firstname, lastname):
    params = {"email": email}
    params.update({"firstname": firstname})
    params.update({"lastname": lastname})
    url = '<your mautic url>/api/contacts/new'
    response = requests.request('POST', url, data=json.dumps(params), headers=headers, auth=('<your login>','<your password>'))
    return response.text

```

the secret is at
*data=json.dumps(params)*, that transforms your parameters into raw json

**Comment by elliott-io** [comment]
I am sending a POST to create a contact using Postman. I have set Body (raw) to:

{
   "email": "testing@domain.com"
}

This still returns an empty contact with a new ID, but doesn't save the email.

Any ideas?

**Comment by mike-sull** [comment]
Change POST to PATCH and /api/contacts/new to /api/contacts/edit

**Comment by igmarinelli** [comment]
Here's my Postman request and it's working perfectly, returning the email not null

![image](https://user-images.githubusercontent.com/18040410/62258882-b01a3880-b3e2-11e9-93cb-da2713f1dfbd.png)
![image](https://user-images.githubusercontent.com/18040410/62258891-b9a3a080-b3e2-11e9-94dc-1584ddb067ed.png)
![image](https://user-images.githubusercontent.com/18040410/62258899-c3c59f00-b3e2-11e9-8820-17ef915ddd06.png)
![image](https://user-images.githubusercontent.com/18040410/62258920-d213bb00-b3e2-11e9-97c8-932b259dc87b.png)
