### ISSUE TITLE
$contactApi->getIdentified(); did not work.

### ISSUE THREAD

**Issue by goroakimoto** [mautic/api-library#124]
Hi. I respect you :)

$contactApi = $api->newApi('contacts', $auth, $api_url);
$response = $contactApi->getIdentified($q);

api-library/lib/Api/Contacts.php

public function getIdentified($search = '', $start = 0, $limit = 0, $orderBy = '', $orderByDir = 'ASC', $publishedOnly = false, $minimal = false)
    {
//         $search .= ($search) ? "$search !is:anonymous" : '!is:anonymous';
        $search = ($search) ? "$search !is:anonymous" : '!is:anonymous';

        return $this->getList($search, $start, $limit, $orderBy, $orderByDir, $publishedOnly, $minimal);
    }

is this modification correct?

**Comment by Celoain** [comment]
I came across the same problem today and applied same fix.

The Problem here is that the searchstring gets repeatet.
`$contactApi->getIdentified(some@ma.il);`
will end up in a searchstring like:
`some@ma.ilsome@ma.il !is:anonymous`

This should be included in the repo asap.
