### ISSUE TITLE
Replace tags with other one

### ISSUE THREAD

**Issue by dhmusman** [mautic/api-library#125]
Hi, I want to replace existing tag, e.g.
example
to
example manager

Is it possible to replace tag, if I try to update the tags, then both tags (example and example manager) are showing in contacts.

**Comment by dhmusman** [comment]
If there is a way to delete a tag that also work for me.

**Comment by mohanprasanthr** [comment]
Try to prepend the minus sign to the tags you want to remove. Like -example. The tags should not be replaced.for more detail refer https://github.com/mautic/api-library/issues/193
