### ISSUE TITLE
Opening and clic not tracked

### ISSUE THREAD

**Issue by drimlike** [mautic/api-library#131]
Hey everyone

I am testing the tracking from an email sent from Mautic. This email is sent via Contact => One of our known contact => Send Email and I select one of our template. Everything seems to be tracked (open email, page hit).  But when I go to Channel => Emails all the stats of the email just sent stay at 0. The good news in incognito window, I am properly tracked except that event. Am I missing something?

I am using Sendgrid, but I logged the path of the link and I can see Sendgrid ==> Mautic ==> site, so surely Mautic know that I clicked on that link from that email? 

I even tested the same scenario and disabled Sendgrid tracking to make sure the only link used is the ones generated by Mautic.  But same result as before.

We are using Mautic v2.9.2 & PHP 5.6.30.

Thanks for your help.

**Comment by escopecz** [comment]
Hi, I think you are asking on wrong repository. Please search https://github.com/mautic/mautic/issues first before you post. Maybe you find an answer.
