### ISSUE TITLE
GET Form Results with API

### ISSUE THREAD

**Issue by sobujbd** [mautic/api-library#135]
Can I get form results with API call?

**Comment by escopecz** [comment]
It is. I wrote docs for it, but it seems they didn't get released yet. Here they are in the pull request: https://github.com/mautic/developer-documentation/pull/69/files#diff-3a8212f6f1884f277fe39ccd557e74a5R439

**Comment by sobujbd** [comment]
But, `getSubmissions`,`getSubmission` isn't defined on method **`Mautic\Api\Form`**?

**Comment by escopecz** [comment]
I just merged https://github.com/mautic/api-library/pull/128, so it is in the dev version of the library.

**Comment by sobujbd** [comment]
Thanks so much, It's working. :heart:
