### ISSUE TITLE
getting error while calling contact api 

### ISSUE THREAD

**Issue by rizwanmindcrew** [mautic/api-library#144]
I am getting this error while calling contacts api

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => 500
                    [message] => The response has unexpected status code (403).

Response: {"errors":[{"message":"Looks like I encountered an error (error #403). If I do it again, please report me to the system administrator!","code":403,"type":null}],"error":{"message":"Looks like I encountered an error (error #403). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":403}}
                )

        )

    [error] => Array
        (
            [code] => 500
            [message] => The response has unexpected status code (403).

Response: {"errors":[{"message":"Looks like I encountered an error (error #403). If I do it again, please report me to the system administrator!","code":403,"type":null}],"error":{"message":"Looks like I encountered an error (error #403). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":403}}
        )

)

Please help me why its happening.

**Comment by escopecz** [comment]
Please look at Mautic logs if you have access. There will be the actual error message.

**Comment by rizwanmindcrew** [comment]
no it does not have any error logs. can it be because of ssl? I am trying to run this on my localhost

**Comment by escopecz** [comment]
If Mautic doesn't have any logs in app/logs directory then it doesn't have correct permission to create those logs.

**Comment by rizwanmindcrew** [comment]
Just having this error in log file.
[2018-01-17 09:05:47] mautic.WARNING: Error accessing https://mautic.com/?feed=rss2&tag=notification : SSL certificate problem: unable to get local issuer certificate [] []

**Comment by escopecz** [comment]
It does seem like a SSL problem then.

**Comment by rizwanmindcrew** [comment]
I am trying this on my local machine so i think ssl should not be the reason for this. 
http://prntscr.com/i1nyir

**Comment by escopecz** [comment]
403 means that authorization failed. Maybe try OAuth 2 if it will make any difference? And don't forget to specify some endpoint.
