### ISSUE TITLE
Why do contributor closes issue before fixing this???? (API not working while I am calling it via proper access token and key)

### ISSUE THREAD

**Issue by rizwanmindcrew** [mautic/api-library#145]
Why contributor on this repo closing issues before fixing. I am not getting proper response from API while I have followed all its documentation. 
You must give actual answer or proper solution before closing it. Its not impressive at all. :(
I am getting this issue since last two days and I am asking solution for the same but they are closing. Can any other help me on this?

Array ( [errors] => Array ( [0] => Array ( [code] => 500 [message] => The response has unexpected status code (401). Response: {"errors":[{"message":"Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator!","code":401,"type":null}],"error":{"message":"Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":401}} ) ) [error] => Array ( [code] => 500 [message] => The response has unexpected status code (401). Response: {"errors":[{"message":"Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator!","code":401,"type":null}],"error":{"message":"Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":401}} ) )

**Comment by dbhurley** [comment]
GitHub is for listing bugs not asking for support help. The issue was closed as a result. You are not reporting a bug but asking for a solution to your problem. You should ask in the forums or Slack chat.

**Comment by skynet** [comment]
API not working for me, either. I don't think Mautic are willing or want to help.

**Comment by escopecz** [comment]
Guys, if you get a 500 error, look into the logs and publish those in the support query or a bug report. Saying that something is not working for you is not enough for anybody to help you.

Read more at https://mautic.org/docs/en/tips/troubleshooting.html
