### ISSUE TITLE
Add optional 3rd parameter to sendToContact()

### ISSUE THREAD

**Issue by yurtesen** [mautic/api-library#150]
Feature Request:
See: https://stackoverflow.com/questions/42402272/

The `sendToContact()` function automatically sends an empty array to `makeRequest()` function. However the actual Mautic API supports sending custom tokens.

```
public function sendToContact($id, $contactId)
{
    return $this->makeRequest($this->endpoint.'/'.$id.'/contact/'.$contactId.'/send', array(), 'POST');
}
```

This could be changed to have `$parameters = array()` as 3rd argument and instead of sending empty `array()` it could send `$parameters` to `makeRequest()` as argument.

**Comment by escopecz** [comment]
Can you send a pull request?

**Comment by yurtesen** [comment]
Is this what you wanted? https://github.com/mautic/api-library/pull/151
Is it going to help anything?

**Comment by escopecz** [comment]
Perfect! Thanks a million!
