### ISSUE TITLE
Error 404 accessing the API

### ISSUE THREAD

**Issue by adrianoGaspar** [mautic/api-library#156]
Helo, I'm trying to access the Mautic API using Basic Authentication. Using the code below
`$contactApi = $api->newApi('contacts', $auth, AC_MAUTIC_URL . "/api");`

I get the answer

`object(Mautic\Api\Contacts)#445 (11) {
  ["endpoint":protected]=>
  string(8) "contacts"
  ["listName":protected]=>
  string(8) "contacts"
  ["itemName":protected]=>
  string(7) "contact"
  ["bcRegexEndpoints":protected]=>
  array(2) {
    ["contacts/(.*?)/dnc/(.*?)/add"]=>
    string(22) "contacts/$1/dnc/add/$2"
    ["contacts/(.*?)/dnc/(.*?)/remove"]=>
    string(25) "contacts/$1/dnc/remove/$2"
  }
  ["searchCommands":protected]=>
  array(11) {
    [0]=>
    string(3) "ids"
    [1]=>
    string(12) "is:anonymous"
    [2]=>
    string(10) "is:unowned"
    [3]=>
    string(7) "is:mine"
    [4]=>
    string(4) "name"
    [5]=>
    string(5) "email"
    [6]=>
    string(7) "segment"
    [7]=>
    string(7) "company"
    [8]=>
    string(5) "owner"
    [9]=>
    string(2) "ip"
    [10]=>
    string(6) "common"
  }
  ["bcTesting"]=>
  bool(false)
  ["endpointsSupported":protected]=>
  array(0) {
  }
  ["bcAttempt":protected]=>
  bool(false)
  ["baseUrl":protected]=>
  string(36) "https://inbound.dentalsigo.com//api/"
  ["auth":"Mautic\Api\Api":private]=>
  object(Mautic\Auth\BasicAuth)#441 (6) {
...
...`

But if I try any command such as seeing a contact passing its id I always get the 404 reply as follows

`array(2) {
  ["errors"]=>
  array(1) {
    [0]=>
    array(3) {
      ["message"]=>
      string(116) "Parece que encontrei um erro (error #404). Se fizer isso novamente, por favor comunique ao administrador do sistema!"
      ["code"]=>
      int(404)
      ["type"]=>
      NULL
    }
  }
  ["error"]=>
  array(2) {
    ["message"]=>
    string(212) "Parece que encontrei um erro (error #404). Se fizer isso novamente, por favor comunique ao administrador do sistema! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)"
    ["code"]=>
    int(404)
  }
}`

I saw that a solution that serves many people is to clear the cache, but for me it did not help. I searched google for many hours for some solution, but none solved my case.

If anyone has any idea how to solve this please help me. Thank you

**Comment by escopecz** [comment]
API enabled? What auth method do you use? What is the URL that returns that 404?

That first response looks like a debug code from var_dump or similar. Are you sure you didn't forget it somewhere in the Mautic code?

**Comment by adrianoGaspar** [comment]
Yes, the API is enabled
![captura de tela 2018-03-28 10 09 17](https://user-images.githubusercontent.com/7820433/38030840-21467550-3270-11e8-9a12-1af1767d1ef5.png)

I use Basic Authentication:

        `define("AC_MAUTIC_URL", "https://inbound.dentalsigo.com/");
        define("AC_MAUTIC_USER", "xxxxxx@xxxxxx.com");
        define("AC_MAUTIC_PASSWORD", "xxxxxxxxxxx");

        // ApiAuth->newAuth() will accept an array of Auth settings
        $settings = array(
            'userName'   => AC_MAUTIC_USER,
            'password'   => AC_MAUTIC_PASSWORD
        );
       
        // Initiate the auth object specifying to use BasicAuth
        $initAuth = new ApiAuth();
        $auth = $initAuth->newAuth($settings, 'BasicAuth');
        $api = new MauticApi();
        $contactApi = $api->newApi('contacts', $auth, AC_MAUTIC_URL . "/api");
        $fields = $contactApi->getFieldList();

        $data = array('firstname' => 'API', 'companyemail' => 'mytest@example.org', 'ipAddress' => '127.0.0.1');
        $response = $contactApi->create($data);

        var_dump($response);`

The $response return 404. The same for;

        `$contactId` =1;
        $response = $contactApi->get($contactId);
        `var_dump($response);`

**Comment by escopecz** [comment]
If you use [API tester](https://github.com/mautic/api-library/tree/master/apitester) you get 404 too?

**Comment by adrianoGaspar** [comment]
I'm using laravel. I tried to use the test api and so far I did not get any type of response, nor the 404. It's a bit complicated to adapt the test api to work with laravel, but I'll keep trying.

**Comment by adrianoGaspar** [comment]
I was able to test the test API. The same 404 error occurs. See the attached video
[erro mautic.zip](https://github.com/mautic/api-library/files/1858417/erro.mautic.zip)

**Comment by escopecz** [comment]
Then it must be the cache problem. Try to clear it with `rm -rf app/cache/*`

**Comment by adrianoGaspar** [comment]
Nothing. I cleaned the mautic caches like you got, cleaned it from Laravel, cleaned it from Chrome and got into the "no-trace" mode of the browser. Even 404.

**Comment by adrianoGaspar** [comment]
thank you John very much the error was on the way to the api (** .with // api)
Now it's working well.

**Comment by ryancwalsh** [comment]
@adrianoGaspar Can you please clarify what the solution was? I've been stuck for days in the same situation that you were in. I know that my credentials aren't the problem because when I provide invalid ones I get "Authorization denied, invalid credentials", as expected. 

I've tried changing my URL to end in `/api/`, `/api`, `/`, and nothing. None of those help.

So I'm confused why I get "Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!" for all the API endpoints. 

And I don't have a `/app/cache` folder to delete. Everyone talks about needing to delete that, but I've never seen one there at all.

Thanks in advance. :-)

cc @escopecz

**Comment by heathdutton** [comment]
@ryancwalsh typically it's cache. If you've enabled the API you must also clear the caches before the API will work without 404.
`rm -rf app/cache/*` is the nuclear cache-clearing option if others do not work.

**Comment by jonaselan** [comment]
I'm in the same situation @ryancwalsh  :(  I using Laravel 5.7

**Comment by ryancwalsh** [comment]
@jonaselan https://stackoverflow.com/questions/49491445/looks-like-i-encountered-an-error-error-404-in-mautic#comment91859340_50724012 You want to delete the `app/cache` folder within the Mautic installation rather than the Laravel installation. And if you are using a VM such as Homestead, you might need to SSH into the VM first.

**Comment by jonaselan** [comment]
Thanks @ryancwalsh, this an important step the I not noticed!

**Comment by iurisilvio** [comment]
Thanks, it was cache. Cleaning cache worked for me.

**Comment by wholanda2** [comment]
Thanks,
I solved the problem by cleaning the cache.

**Comment by souzadavi** [comment]
me too...

**Comment by prosenjitsarkar** [comment]
I have same issue , But i don't have cache folder 
And my url doesn't have "//"

**Comment by Pamblam** [comment]
What the hell!

I had the same 404 issue with the api. I did exactly as described here as well as in several other places around the web: `rm -rf app/cache/*`

Now the 404 is a 500! And the entire app is broken.

In the logs:

    [2019-11-12 19:43:39] mautic.ERROR: PHP Notice: require(): Failed opening required '/home/runcloud/webapps/mautic/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:') - in file /home/runcloud/webapps/mautic/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []

I copied the entire contents of another instance's `app/cache` folder to replace all the stuff you told me to delete and it works again, but why did that happen in the first place? Why advise people to delete files that are clearly necessary?

**Comment by escopecz** [comment]
Mautic (web server linux user) did not have permission to write the new cache files on refresh.

**Comment by Pamblam** [comment]
I `chmod -R 777 app/cache/` before restoring the entire directory and that didn't help. Also, before doing so I checked that `app/cache` was writable via the app's own *system info -> file and folder settings* page. Is there something else that needs permissions?

**Comment by escopecz** [comment]
chmod is one part to check. The file/folder owner is the other. All Mautic files and folders must be writable. You should use recursion for that. It must have permission to modify its files during upgrades. But especially all files and folders in app/cache including the app/cache folder must be writable.

**Comment by papr-i-ka** [comment]
@escopecz I tried clearing cache, but again 404. Any help ?

**Comment by peter-palmer** [comment]
I still having trouble with this. I don't found any folder called cache, I have searched inside `/bin` and `/app` directories and there is no such `/cache` directory.

I'm getting the following error:
```
{
    "errors": [
        {
            "message": "Requested URL not found: /api/contacts",
            "code": 404,
            "type": null
        }
    ]
}
```

The authorization header is correct, because if I modify it I get Unauthorized error. I'm using Basic Auth.

Could someone help me with this please?

Thanks!

**Comment by RCheesley** [comment]
Hey there, the cache is in var/cache since Mautic 3.

**Comment by peter-palmer** [comment]
> Hey there, the cache is in var/cache since Mautic 3.

So I have delete it, and now I'm getting another error:

`Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://my-domain.com/api/contacts`

**Comment by peter-palmer** [comment]
> Hey there, the cache is in var/cache since Mautic 3.

It is working, thanks a lot for the fast reply!
