### ISSUE TITLE
Error code 404 when request API 

### ISSUE THREAD

**Issue by dennisgon** [mautic/api-library#158]
I try to request Mautic API with an end point http://localhost/api/contacts/1 and I got the following error

`{
    "errors": [
        {
            "message": "Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!",
            "code": 404,
            "type": null
        }
    ],
    "error": {
        "message": "Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)",
        "code": 404
    }
}`

I already clear my mautic cache but it didn't resolved my problem. And i already check the logs but there isn't error
can you help me

**Comment by escopecz** [comment]
Read through https://github.com/mautic/api-library/issues/156

**Comment by escopecz** [comment]
We were discussing several possible fixes in that topic. Mostly clearing the Mautic cache will help. The problem there was the hew as putting there `http://somedomain.com/` in it and the library then tried to access `http://somedomain.com//api`. Those are the double slashes that were causing the problem.

**Comment by dennisgon** [comment]
@escopecz i already tried with end point like http://somedomain.com/ and http://somedomain.com//api and the result it still same also i already try to clear the cache with this tutorial https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by escopecz** [comment]
There should not be two slashes is what I'm trying to tell you. If you place `var_dump($options);die;` on this line: https://github.com/mautic/api-library/blob/master/lib/Auth/AbstractAuth.php#L175 What is the output? (censor sensitive information before posting)

**Comment by dennisgon** [comment]
@escopecz thanks for the solution  i already find the solution so i delete manualy all of the cache file and change the permision of the new cache file that mautic's created but when i open http://localhost/api/ the error still same but when i open http://localhost/api/contacts it show the result

**Comment by escopecz** [comment]
Coo, so it's working as it should. `http://localhost/api/` is not a valid endpoint.

**Comment by prosenjitsarkar** [comment]
Hi John , 

I have installed in my local machine , so no cache 
i didnt use "//" but still have 404 while trying to get contacts

Please help

**Comment by Woeler** [comment]
If you turned the API on via the backend there is cache and you should clear it.

**Comment by prosenjitsarkar** [comment]
I am using windows system , i have xampp . Where exactly cache folder present ?
or how to remove ?

**Comment by Woeler** [comment]
`app/cache/prod`

**Comment by prosenjitsarkar** [comment]
This is my folder structure

**Comment by prosenjitsarkar** [comment]
Sorry I dont have any app/cache/prod

**Comment by escopecz** [comment]
You'll find the app/cache/prod folder in the Mautic root directory.

**Comment by basantk** [comment]
Delete Cache it will works

**Comment by basantk** [comment]
delete app/cache from mautic project folder.

**Comment by mvfpoa** [comment]
For those hitting this and unable to solve even after a cache clear, I would suggest to remove a trailling slash. That was what solved my problem. I typed "http://my-mautic.server.com/api/", but the correct form is  "http://my-mautic.server.com/api". Good luck!

**Comment by sheldoncoupeheure** [comment]
ran `rm -rf app/cache` and it worked

**Comment by manfredjb** [comment]
In my case, I solved it by removing the cache in another directory: `var/cache/prod/`. Run:

    rm -rf var/cache/prod/*

If `/*` is not presented, then the prod directory is removed and may occours problems in the future.

**Comment by ariyo** [comment]
For people who may still be running into this. In my case I fixed it on my instance. Read on...

I cleared cache and everything **stoped** working. Refreshed Mautic on the browser and I got the "contact your administrator" error 😱 ! Looking at the logs I saw that the cache folder was not writeable. I fixed it by running: 
`sudo chown -R www-data:www-data /var/www/html` --> Read the fix below before your run this command.
Then I refreshed the browser and everything was running again!   

The actual FIX:
Turned out the API endpoint was not `https://your-mautic-instance.com/api` it is `https://you-mautic-instance.com/index.php/api `  in fact to get the accurate base url, go to your Mautic configuration > System Settings and look at the `Site URL` That should be your API base URL. That was simply what it was for me. I hope it helps someone out there!

**Comment by escopecz** [comment]
@ariyo thank you for your experience! I'm sure it will help others in similar situation.There are a couple of things that should not happen though so I want to point them out that it's not how it's suppose to be.

1. Mautic did not have permission to write into the cache directory. The right permissions and ownership should have been configured during installation of Mautic.
2. If you have to use `index.php` in your Mautic URL then you don't have properly configured server. Check if `.htaccess` and `mod_rewrite` is enabled. It should not be there.

**Comment by MagedMRawash** [comment]
i tried to clear cache & checked the URL, but not working for me. 
the issue was in my additional parameters .. removed then it works fine for me :)

**Comment by Aerendir** [comment]
Sometimes the error is the HTTP method used.

For example, if you call `api/contacts/new` using a `GET`HTTP method, then you will get a 404 error.
If you, instead, use the `POST` HTTP method, then the API works.
