### ISSUE TITLE
Authorisation between Mautic 2.13.x API and Magento 1.9.x

### ISSUE THREAD

**Issue by FrennsDeveloper** [mautic/api-library#160]
We are trying to authenticate the MageDirect Mautic-Magento module through Oauth1/2 on our Mautic 2.13.x on our Magento 1.9.x server.

We copy the clientID and the secret keys int MAgento but then get the following erros:
We keep getting either:
OAuth1 Error
Incorrect access token parameters returned: Array
Please check Mautic authorization credentials!

OAuth2 Error
Incorrect access token parameters returned: Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!
Please check Mautic authorization credentials!

And we cannot even get to the User we have set up specifically for the integration. After having searched the internet we have realised that this is nothing someone else seem to have.

What to do?

**Comment by escopecz** [comment]
It looks like you've misconfigured the API credentials. Make sure you use the right Oauth version credentials. And the return URL must match.

**Comment by FrennsDeveloper** [comment]
We have tried all kinds of solutions hre.

The problem is that the error messages are preceeding the API credentials we need to type in so we never get to the API credentials. 
Or are there any files we need to change with the API credentials.

I have pasted some screen dumps in the attached files where you see the dialogues. Those dialogues are right before the API credentials are supposed to show up.

[Document0.pdf](https://github.com/mautic/api-library/files/2052863/Document0.pdf)

**Comment by escopecz** [comment]
You have to authorize as the first thing you do. Authorization will return the access token that you'll use for API calls. Example here: https://github.com/mautic/api-library#authorization

**Comment by FrennsDeveloper** [comment]
Yes, that is what we do through the GUI as you can see from the attached files, but we cannot login to Mautic. 
We have cleared the Magento cache as everyone says, but then when we press the button Authorise is shows the popup.
Behind the hidden squares it is clientID and the hidden is the secret key exactly as when you show in the code you linked to it is only through the GUI instead of through the file, but still it says there is an error.

What would you suggest to do?

**Comment by escopecz** [comment]
Clear Mautic cache: https://www.mautic.org/docs/en/tips/troubleshooting.html
