### ISSUE TITLE
Run tests in Travis

### ISSUE THREAD

**Issue by heathdutton** [mautic/api-library#167]
We should add travis CI to this repo to avoid regressions.

This will need to clone mautic (staging) locally, install it, enable and configure twilio plugin (via cli,  somehow), then run phpunit tests for each auth method in this repo. Basic, OAuth1a and OAuth2. The tests should be ran for the same versions of PHP as the Mautic core tests. It'll take a while, but it'll be worth it.

I imagine it might be good to have the test ran daily.

**Comment by RCheesley** [comment]
Closing this now as we are not using Travis any more and we already have daily tests running 🙌 🚀
