### ISSUE TITLE
Where to put Mautic API in Mautic administration folder

### ISSUE THREAD

**Issue by nyel-dev** [mautic/api-library#168]
I have mautic admin and the directory is like this:

* app
* media
* plugins
* themes
* translations
* vendors

I have found the mautic files inside /app/bundles

now I am trying to install the API manually. Where should I put it and how do I load the files?

**Comment by escopecz** [comment]
Mautic has API built in. This PHP library is helper library to connect 3rd party PHP apps with Mautic via API.
