### ISSUE TITLE
 how to add contacts to a segment

### ISSUE THREAD

**Issue by pirojok167** [mautic/api-library#173]
How to add contacts to a segment?

I created 100 contacts and 1 segment.
I want to add them to the segment.

How do I do that with mautic api?

**Comment by escopecz** [comment]
https://developer.mautic.org/#add-contact-to-a-segment

**Comment by pirojok167** [comment]
No. This the addition of a single contact. I want to add some contacts to the segment.

**Comment by escopecz** [comment]
You can still loop over them and add one by one.

Or add them to a special tag and use the segment filters to do their job. There is no batch contact add to segment endpoint AFAIK.

**Comment by pirojok167** [comment]
I can not use the loop. If I add 1000 contacts, then these are 1000 requests.

**Comment by pirojok167** [comment]
Your answer helped me. I add contacts to the segments using tags.
But I installed mautic on the local machine. And here it does not work.

I have a segment with a tag test.
![1](https://user-images.githubusercontent.com/29654415/48261326-bbca6700-e42f-11e8-92e1-8511e9e65eb8.PNG)

And I have a contact with a test tag.
![2](https://user-images.githubusercontent.com/29654415/48261391-01872f80-e430-11e8-892b-8c50a6480275.PNG)

But the segment has no contacts.
![3](https://user-images.githubusercontent.com/29654415/48261412-0ea41e80-e430-11e8-8108-580e9403a979.PNG)

I use mautic 2.14.2
php 7.1

**Comment by escopecz** [comment]
Cron jobs are configured?

**Comment by pirojok167** [comment]
No. Does crown affect tags?

**Comment by escopecz** [comment]
Cron jobs rebuild segments https://www.mautic.org/docs/en/setup/getting_started.html

**Comment by pirojok167** [comment]
I did not notice. Thank you very much.
