### ISSUE TITLE
Feature request: Add note to lead

### ISSUE THREAD

**Issue by kuzmany** [mautic/api-library#18]
I would like add to lead note about his website action (order, cart items...).

**Comment by escopecz** [comment]
I'm sorry, could you expand your request a bit? I don't think a developer can do something based on your sentence. For example what would you add to a lead note? That part is missing completely.

**Comment by kuzmany** [comment]
Okay, sorry.

I would like add lead note via API. 
For example If my customer make order on my website,  I want make notes about his order. (what he order, which time, which delivery servis etc.)
But I think there is a lot of another examples.

**Comment by moskoweb** [comment]
Hello @kuzmany, with the current API already out of the way to do this, the only question that does not get well explained is how to create the note already in the lead.

After breaking my head a bit, I was able to create a look at the API Documentation settings request I made in the Create Note section, which will make it clear how to do it.

https://github.com/moskoweb/developer-documentation/blob/6189f51c8e9b5fc741ff0fac47ea77004cad164a/source/includes/_api_endpoint_notes.md
