### ISSUE TITLE
Duplicate contacts created by Mautic and API.

### ISSUE THREAD

**Issue by krnowakowski** [mautic/api-library#190]
When I create a contact via API, it is created separately to the one which Mautic system creates automatically when a user hits my website. Therefore, I end up with two copies of the same contact (screenshots attached):
- one anonymous created automatically by Mautic, with full history of page hits
- one created via API - with all information sent via the interface

Could you please advise how to make Mautic see that the information sent via API is for the previously anonymous user and not a new one?

![Mautic-contact-issue-2](https://user-images.githubusercontent.com/49908409/56580244-698e9400-65d2-11e9-9599-8bf2babcc9ae.png)
![Mautic-contact-issue-1](https://user-images.githubusercontent.com/49908409/56580245-6a272a80-65d2-11e9-8ef8-d2b5cb967706.png)

**Comment by Woeler** [comment]
You should read the contact ID from the Mautic cookie and send it with the contact request (and use the update request, not the create)

**Comment by escopecz** [comment]
You have to tell Mautic somehow that it should update or create new contact (please don't use user as it is different entity in Mautic). Mautic will automatically merge contacts by the email address. But the anonymous contact doesn't have one.

Let's start with the question how did you find out that those contacts should be merged?

**Comment by krnowakowski** [comment]
@Woeler : thanks a lot, I'll try that. Is it stored in $_COOKIE['mtc_id']?

@escopecz : at the moment I've stopped all advertising activities, therefore I have very low traffic, which makes it easy to match contacts using time and location. I didn't have a clue how to tell Mautic to update an existing anonymous contact. Do I get her/his ID from $_COOKIE['mtc_id']?

**Comment by krnowakowski** [comment]
Solved, thanks a lot for your help! :)

**Comment by bilaalabdelhassan** [comment]
@krzysztofmn  How did you update your existing contact which already have an ID with the anonymous ID history details?
