### ISSUE TITLE
Contact Tags not updated properly in mautic REST API

### ISSUE THREAD

**Issue by mohanprasanthr** [mautic/api-library#193]
Hi,
i have create a contact with tags like "tamil,english,hindi"..when i update the contact using API the tags are not get replaced. for example if i update new tag it will add along with existing tag it cannot replace it

**example :**  
**created contact tags :** tamil,english,hindi
**updated contact tags :** tamil
**issue** : but it still shows all the three tags for the particular contact.

**Comment by escopecz** [comment]
Try to prepend the minus sign to the tags you want to remove. Like `-tamil`. The tags should not be replaced.

**Comment by mohanprasanthr** [comment]
Thank you very much..it works fine
