### ISSUE TITLE
Mautic REST API - Couldn't able to update the created and modified user id for the contact

### ISSUE THREAD

**Issue by mohanprasanthr** [mautic/api-library#199]
I was trying to update the user id to the leads table (created_by and modified_by)but it always update the user id 1 to the contact.
below is the code for your reference,
```
Array
(
    [firstname] => Mohan 2
    [lastname] => w
    [email] => Mohan2@moh.com
    [mobile] => 944706999
    [facebook] => 
    [twitter] => 
    [points] => 10.00
    [tags] => Young
    [trails] => 1
    [createdBy] => 61
    [createdByUser] => Mohan
)
$contact = $leadApi->create($data);
```

**Comment by escopecz** [comment]
Created/updated by are internal Mautic properties. Those should not be updatable via API, import or UI. It will use the user who created the API credentials.
