### ISSUE TITLE
Cannot update lead

### ISSUE THREAD

**Issue by ciprianMihalache** [mautic/api-library#20]
$leadApi = \Mautic\MauticApi::getContext(
                    "leads", $auth, $mauticBaseUrl . '/api/'
    );
    

 $filter = 'email:' . $updatedData['email'];
 $leads = $leadApi->getList($filter);

if (!empty($leads)) {
            $leadId = $leads['leads'][0]['id'];
            if (!empty($leadId)) {             
                // If you want to create a new lead in the case that $leadId no longer exists
// $result will be populated with the new lead item
                $result = $leadApi->edit($leadId, $updatedData);
            } else {
                echo 'No leadId';
            }
        } else {
            echo 'New lead';
            $result = $leadApi->create($updatedData);
        }

I tested with an existing email and the mautic server response with the leadID. But when I try to update nothing happens.

**Comment by ciprianMihalache** [comment]
$updatedData['email'] = $user_email;
$updatedData['zipcode'] = $user_zipcode;
$updatedData['city'] = $user_city;

**Comment by ciprianMihalache** [comment]
I managed to found out the bug

So you have this function

 $result = $leadApi->edit($leadId, $updatedData);


If the array $updatedData contains fields that are not on lead fields there is no response from server

Example:

CORRECT
$updatedData  = array();
$updatedData['email'] = $email;
$updatedData['zipcode'] = $zipcode;
 $result = $leadApi->edit($leadId, $updatedData); //response from server, everything is correct

WRONG
$updatedData  = array();
$updatedData['email'] = $email;
$updatedData['zipcode'] = $zipcode;
$updatedData['new_filed'] = $new; //field is not created on mautic platform
 $result = $leadApi->edit($leadId, $updatedData); //empty array from server.

I guess you can ignore fields no present on lead fields.

**Comment by FrancescJR** [comment]
I guess you should update field by field in case any of them are non-present so at least you can still update the other fields
