### ISSUE TITLE
Create contact overwrites existing contact

### ISSUE THREAD

**Issue by robov** [mautic/api-library#201]
When I create a new contact with an existing email, then the existing contact is overwritten, no warnings whatsoever.
This feels a bit wierd and unreliable

**Comment by escopecz** [comment]
It has been a PR from the community https://github.com/mautic/mautic/pull/3317

It seems that most people are OK with how it works now. I don't see any suggestion in your issue 
and also it's a feature of Mautic, not this API library so I'll close it.

**Comment by robov** [comment]
Ok, it is just a bit confision, there is an edit with a create param if not exist. but explicitly calling only create with a contact is a bit confusing.
Maybe a tip to add comments to your create function that this will overwrite the contact with the email if it exists.

**Comment by robov** [comment]
BUT.. thank you for creating this library... once getting used to it, it works smooth
