### ISSUE TITLE
API Performance so slow it becomes unusable

### ISSUE THREAD

**Issue by DevHeaven** [mautic/api-library#204]
I've just started experimenting with the Mautic API but I'm running into issues with performance.
I'm using the contactApi Create method to add subscribers but on average it takes about 2.9 seconds for 1 subscriber to be added.

My code is very straightforward. I have an array that contains email,firstname,lastname , I run through the array calling the API method. For the example below there are 10 elements in the array and the run takes 29.5 seconds

`
foreach ($result as $member){

  $data['email'] = $member->emailid;
  $data['firstname'] = $member->fname;
  $data['lastname'] = $member->lname;
  $response = $contactApi->create($data);
  $contact = $response[$contactApi->itemName()];		
}
`

**Comment by ithieund** [comment]
Hello @escopecz , I faced with the same issue with Mautic 3
On the newly installed instance, the API used is /users/self took more than 1 seconds to response, which is too slow for a simple action
![image](https://user-images.githubusercontent.com/4217195/140288407-3cdb2223-2d3d-4aea-85ad-a17a76702ec9.png)

Then in another instance with 12K contacts, it took 3 seconds for the api /users/self to response.
![image](https://user-images.githubusercontent.com/4217195/140290554-7bc65c07-e88f-49ca-81a4-c2ef9c80f372.png)

Could you explain with cause it so slow and how to optimize it?
Thanks.

**Comment by escopecz** [comment]
It depends on the hardware and your server configuration. I'm not really a DevOps guy so would I focus on profiling. There are several tools for PHP profiling like Tideways that will show you what is happening, how long it takes, how much memory it takes and what the bottlenecks are. Then you'll know where to look for optimizations.
