### ISSUE TITLE
Bug related to using json_encode instead of http_build_query

### ISSUE THREAD

**Issue by ghost** [mautic/api-library#216]
Using json_encode instead of http_build_query works nicely with Basic Auth with both POST and GET but for Oauth2 only GET works.. so if you tried to create a contact using Oauth you will get this error

errors: { 0: { code: "401", message: "The response has unexpected status code (401)." }

**Comment by benlumley** [comment]
This fix works for me + should be merged...

**Comment by dennisameling** [comment]
Fixed in https://github.com/mautic/api-library/pull/217 which has now been merged. Thanks for reporting this!
