### ISSUE TITLE
OAuth::makeRequest #L 746 - Problem in symfony 1.0.2

### ISSUE THREAD

**Issue by lluistfc** [mautic/api-library#25]
I've been implementing a script to get data from our private Mautic and found this little problem.

On [OAuth::makeRequest #L 746](https://github.com/mautic/api-library/blob/master/lib/Auth/OAuth.php#L746) 

`$options[CURLOPT_POSTFIELDS] = http_build_query($parameters);`

While this works fine with the apitester, in symfony 1.0.2 the function `http_build_query` encodes the `&` as `&amp;` causing a failure in the request for a token.

I've solved it by modifying this line like this:

`$options[CURLOPT_POSTFIELDS] = http_build_query($parameters, '', '&');`

Is it possible to make a little modification to check if the `http_build_query`actually builds the postfields correctly?

**Comment by escopecz** [comment]
Could you send a pull request?

**Comment by lluistfc** [comment]
done
