### ISSUE TITLE
Usage of newer psr/log (v2 & v3)

### ISSUE THREAD

**Issue by jonnitto** [mautic/api-library#268]
Currently, `psr/log` is set to version 1. Because of that, it is not possible to use this package in some enviroments

**Comment by escopecz** [comment]
Good point. Are you able to make a PR?

**Comment by dakur** [comment]
@escopecz Could you also make a release, please?

**Comment by escopecz** [comment]
@dakur done: https://github.com/mautic/api-library/releases/tag/3.1.0
