### ISSUE TITLE
Bad Request is treated as a valid response

### ISSUE THREAD

**Issue by Aurielle** [mautic/api-library#27]
Trying to create a lead with invalid data (bad country in my case) leads to 400 Bad Request from Mautic and empty JSON object (`{}`) being returned. Yet the library still treats this as a valid response, because it looks at the JSON, which is valid, and does not check the headers and status code.

This behavior is partly also Mautic's fault, because there should be an error description aside from the non 2XX status code.

**Comment by escopecz** [comment]
Should be fixed in Mautic 2.1.1
