### ISSUE TITLE
How to set the last_active field? And is there any way to set the dateAdded/dateModified/dateIdentified fields?

### ISSUE THREAD

**Issue by vesper8** [mautic/api-library#291]
Something went wrong and we stopped adding new leads automatically for a couple of weeks. So now I've fixed the issue and I need to go through the backlog and add all the contacts that should have been added but weren't. It would be convenient to be able to set the date fields.

Is there a way to set the "internal" fields dateAdded/dateModified/dateIdentified via the API?

And what about the "last_active" field? I see this field is actually in the list or lead fields, but I tried passing it a date object and got not error but it also didn't seem to have any effect.

Many thanks

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
