### ISSUE TITLE
Deprecated  strlen(): Passing null to parameter #1 ($string) of type string is deprecated PHP 8.1.12

### ISSUE THREAD

**Issue by LadySolveig** [mautic/api-library#292]
Some lines with deprecated messages in PHP 8.1 - api-library/lib/Auth/OAuth.php

Deprecated
: strlen(): Passing null to parameter 1 ($string) of type string is deprecated in api-library/lib/Auth/OAuth.php on 
- line 388
- line 395
- line 637

PR #293

**Comment by mollux** [comment]
closed in #293
