### ISSUE TITLE
deprecated: ApiAuth::initiate & MauticApi::getContext

### ISSUE THREAD

**Issue by davout1806** [mautic/api-library#31]
I see that ApiAuth::initiate & MauticApi::getContext were both deprecated and replaced with non-static methods for testing purposes. Should users of the API continue to use the static methods or switch to the non-static methods. If the later, then maybe add note on what should be used.

**Comment by escopecz** [comment]
Readme with code examples uses the new methods. Could you clarify where else you suggest to put some note and what the note should say? Maybe send a PR with it?
