### ISSUE TITLE
KiCad API Could not connect

### ISSUE THREAD

**Issue by pdo59** [mautic/api-library#318]
I tried to use the API with Kicad, but I get the message: "Could not connect to  http://partdb.lan/en/kicad-api/v1/. Errors: API responded with error code: 301: Moved Permanently
With `curl -k` I receive the response: `{"categories":"","parts":""}`
The root_url in the user settings is shown as: http://partdb.lan/en/kicad-api/ and this is the value I wrote in the partd.kicad_httplib file.
The Kicad version is 7.99 dec 01 [kicad-unified-universal-20231201-0910-2d9eee93e2.dmg] 

PS In API PLATFORM the system seems to be responsive, I have successfully tried `/api/users` and others

**Comment by escopecz** [comment]
This is API SDK to connect to a Mautic instance. I guess there has been some misunderstanding. This library is not related to Kicad in any way.
