### ISSUE TITLE
API methods changed in v2.0?

### ISSUE THREAD

**Issue by startfinance** [mautic/api-library#42]
Has the API changed in v2.0? I am not being able to connect using the methods that worked before.

**Comment by escopecz** [comment]
I don't think so. Try to clear the cache and if that won't help, study the error messages stored in the logs. It might reveal some problem.

**Comment by escopecz** [comment]
Looking more closely, it seems that 'leads' endpoints were renamed to 'contacts' and `lists` to `segments`, but there seems to be a bug when I use the new endpoints anyway. I'll try to fix it.
