### ISSUE TITLE
Support authentication via CLI

### ISSUE THREAD

**Issue by ipso** [mautic/api-library#45]
I'm attempting to use the API to manage many contacts/segments in a more automated fashion from a PHP CLI script. However it appears as though the API with OAuth authentication isn't designed for this, as it wants to redirect the CLI script to a URI to login. Of course with no web browser attached this fails everytime. 

Is this possible and if so, is there an example CLI script that can access the Mautic API by chance?

**Comment by alanhartless** [comment]
This is a weakness in the API. The workaround is to use a oauth1a client
with a 3rd party script (or the API tester included) to authenticate with
Mautic. Then grab the access token and code that into your CLI process.
Oauth1a tokens do not expire unless revoked (unlike oauth2).

**Comment by ipso** [comment]
Could I trouble you for a brief example showing the best practice on how to use the obtained access token with the API library directly perhaps? I thought I had it working, but I still seem to be getting redirected to a URL.

**Comment by vkathirvel** [comment]
I second this. I am writing a case where I use the API to pull and push data from a remote application without a user interface. Something that punches leads and updates based on the visitor's activity.

**Comment by vkathirvel** [comment]
I managed to copy across the details from the oauth1 access tokens table and getting this error now
"Requested URL not found: /api/leads/new"
Any ideas?

**Comment by escopecz** [comment]
@vkathirvel you are probably using Mautic 2.x.x. Leads were renamed to contacts. Check updated documentation: https://developer.mautic.org/#contacts

**Comment by vkathirvel** [comment]
Thanks John! My bad. I was using the version 1 branch of the API library.

**Comment by ipso** [comment]
@vkathirvel Did I read that right, that you were able to get the API library working from the CLI? If so, could you provide some more details or example of what you did perhaps?

**Comment by fcatanzaro** [comment]
I connected via CLI with no issues whatsoever.  Oauth2 already supports the "password" grant type and that worked just fine all in the clip with no interaction.  At some point I had added the grant type password to the oauth2 database table but I'm not sure that was even needed since Mautic uses a standard OAuth library... I can post sample if you would like.

**Comment by ipso** [comment]
Yes, I'm still struggling to get this working, so any examples would be appreciated.

**Comment by fcatanzaro** [comment]
@ipso Here is what I did, I just did it again to make sure it all works, step by step. It involves no modification to Mautic codebase, but there is one query to run.

1. Create an OAuth2 API credentials in Mautic.  The redirect URI is irrelevant for this example, so put in anything.  Note the "ID" of the credentials (it's the primary key in mysql).

1. Open a mysql editor connected to the mautic database, and run the following query: 
"update oauth2_clients set allowed_grant_types = 'a:3:{i:0;s:18:"authorization_code";i:1;s:13:"refresh_token";i:2;s:8:"password";}' where id = 3;"  (replace id = 3 with whatever the ID of your credentials are as per step 1.  This is just a serialized string telling oauth which credential types to allow, I added the last piece, "password".
1. At this point you've done nothing to Mautic itself.  At this point password grant OAuth2 works fine.  Here is some sample code that connectes to Mautic and successfully gets a token, all without user interaction:
```php
<?php

	$data = array(
	'grant_type' => 'password',
	'username' => "adminuser",
	'password' => "adminpass",
	'client_id' => "clientidstring",
	'client_secret' => "clientsecretstring"
	);

	$query = http_build_query($data);

	$curl = curl_init("httpw://myurlformautic.com/oauth/v2/token");
	curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($curl, CURLOPT_POST, true);
	curl_setopt($curl, CURLOPT_POSTFIELDS, $query);
	curl_setopt($curl, CURLOPT_HTTPHEADER, 
	array('Accept: application/json','Content-Type: application/x-www-form-urlencoded'));

	$body = curl_exec($curl);
	$response_code = curl_getinfo($curl, CURLINFO_HTTP_CODE);
	curl_close($curl);

	$resp = json_decode($body, true);

	print_r($resp);

if(empty($resp['access_token'])){
	die("no token");
}
$settings['accessToken']        = $resp['access_token'];
$settings['accessTokenExpires'] = $resp['expires_in']; 
$settings['refreshToken']       = $resp['refresh_token'];
```

**Comment by vkathirvel** [comment]
@ipso I've done a similar thing with oAuth1a.

@fcatanzaro Will the oAuth2 setup detailed in your setup work in a non-https environment? Or, does it require https?

**Comment by fcatanzaro** [comment]
@vkathirvel It worked without https, but of course not a good idea and no guarantee that OAuth module won't kill (fix?) at some point.  Free SSL certs at https://letsencrypt.org/ solve that problem.

**Comment by vkathirvel** [comment]
Thanks @fcatanzaro

**Comment by ipso** [comment]
@fcatanzaro Thanks, that helped a ton!

**Comment by ipso** [comment]
So I was able to create a CLI API script that gets leads and creates new ones, but when I attempt to edit an existing lead I get the following API result everytime:

```
array(1) {
  ["error"]=>
  array(2) {
    ["code"]=>
    int(500)
    ["message"]=>
    string(233) "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /api/contacts/225014/edit
on this server.<br />
</p>
</body></html>
"
  }
}
```

Even if I create the lead with the API, then immediately try to edit the one I just created the above error occurs. Am I missing something obvious here perhaps? I can edit the contact from the web UI without a problem of course.

**Comment by fernandolcardoso** [comment]
Add this line

curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

To access the https url

**Comment by escopecz** [comment]
I think we can close this issue since the [Basic Auth](https://developer.mautic.org/#basic-authentication) was implemented. No redirect in the browser required there.
