### ISSUE TITLE
better docs for authorization

### ISSUE THREAD

**Issue by vectorbross** [mautic/api-library#53]
I can't get the authorization API to work. From what I can tell from the Mautic documentation, you either have to the authorization manually or use the API. I can't get the API to work, without the user needing to confirm access from Mautic. I thought this would have been possible by using the tokens generated with OAuth1a, but as I make the first call to the contact API, I get an invalid token error.
This is what I tried:

```
<?php
// ApiAuth::initiate will accept an array of OAuth settings
$mauticSettings = array(
        'baseUrl' => 'http://example.net',       // Base URL of the Mautic instance
        'version' => 'OAuth1a', // Version of the OAuth can be OAuth2 or OAuth1a. OAuth2 is the default value.
        'clientKey' => 'key',       // Client/Consumer key from Mautic
        'clientSecret' => 'secret',       // Client/Consumer secret key from Mautic
        'callback' => 'http://example.com/account/index2.php'        // Redirect URI/Callback URI for this script
);

// Initiate the auth object
$auth = new ApiAuth();
$auth = $auth->newAuth($mauticSettings);

// Initiate process for obtaining an access token; this will redirect the user to the $authorizationUrl and/or
// set the access_tokens when the user is redirected back after granting authorization

// If the access token is expired, and a refresh token is set above, then a new access token will be requested

try {
    if ($auth->validateAccessToken()) {

        // Obtain the access token returned; call accessTokenUpdated() to catch if the token was updated via a
        // refresh token

        // $accessTokenData will have the following keys:
        // For OAuth1.0a: access_token, access_token_secret, expires
        // For OAuth2: access_token, expires, token_type, refresh_token
        if ($auth->accessTokenUpdated()) {
            $accessTokenData = $auth->getAccessTokenData();

            //store access token data however you want
        }
    }
} catch (Exception $e) {
    die($e->message);
}

$mauticApi = new MauticApi();
$contactApi = $mauticApi->newApi('contacts', $auth, 'http://mautic.v-b.be/api');
$contact = $contactApi->get(1);
$mauticMessage = print_r($accessTokenData, true).print_r($contact, true);
?>
```

**Comment by escopecz** [comment]
Note the `//store access token data however you want` comment in the code you posted. That's where you should store the access token and use it in the future API calls. Or is there another problem I don't see?

**Comment by vectorbross** [comment]
The problem is that I don't get the access token data. Instead, I get the error message invalid_signature (code 401).

**Comment by vectorbross** [comment]
I did change the line `$auth->newAuth($mauticSettings);` to `$auth = $auth->newAuth($mauticSettings);`, which is different from the readme, but when I do it like the readme, I get an exception the method validateAccessToken cannot be found.

**Comment by escopecz** [comment]
Double-check that your keys are properly copy-pasted form your Mautic. It seems they are not. If you test it with the API Tester, does the OAuth1a connection work?

**Comment by vectorbross** [comment]
How do I use the API Tester?

**Comment by vectorbross** [comment]
Yes, when I try to authorize with the API tester, OAuth1a labels become green (I suppose that means authorization was successful).

**Comment by vectorbross** [comment]
Why does the tester work without login? I'd like to be able to use like the tester, but I'm always asked to log into Mautic.

**Comment by vectorbross** [comment]
Apparently there is no way to get the token data using OAuth1a. I had to print out the ApiAuth object to get at the tokens. Once I got the tokens, I got it to work.

**Comment by vectorbross** [comment]
I think this should be put in the readme, or else a better approach must be found for OAuth1a.

**Comment by escopecz** [comment]
1. You have to log in once to get the access  token. Even in the API tester.
2. If you can use the OAuth1a working API tester, it means that it is working, right?

**Comment by escopecz** [comment]
Please check https://github.com/mautic/api-library/pull/60 if it solves your issue.

**Comment by TiagoGouvea** [comment]
The docs are really poor, the samples just don't work.
