### ISSUE TITLE
functions not found

### ISSUE THREAD

**Issue by ascalabro** [mautic/api-library#58]
If using example in README.md, `$auth->validateAccessToken()`, `$auth->accessTokenUpdated()`, and `$auth->getAccessTokenData()` will not be found for the `ApiAuth` object calling them. 
The functions exist for the object returned from `ApiAuth::newAuth()`, so if setting `$auth` to that like `$auth = $auth->newAuth($settings)`, the functions will exist.

**Comment by escopecz** [comment]
Please check https://github.com/mautic/api-library/pull/60 if it can be like that.

**Comment by ascalabro** [comment]
Looks like #60 does the trick I mentioned
