### ISSUE TITLE
Obtaining an Access Token

### ISSUE THREAD

**Issue by nickian** [mautic/api-library#59]
Am I missing something here? I used the example code in the readme file, but I'm never redirected to the app. I just get this error:

**Fatal error: Call to undefined method Mautic\Auth\ApiAuth::validateAccessToken()**

That's with this code:

```
<?php

// Bootup the Composer autoloader
include __DIR__ . '/vendor/autoload.php';

use Mautic\Auth\ApiAuth;

$publicKey = '24gnw4fpxu3o8s4ws8ccsccwoso48ccw44s0c84s0owgscgk0w';
$secretKey = 'ky7juiwu3hcgks8coco0kcs8ocsss8o4oo40gokccw04cks0g';
$callback  = 'http://local.dev';

// ApiAuth::initiate will accept an array of OAuth settings
$settings = array(
    'baseUrl'          => 'https://mymauticinstallation.com',     
    'version'          => 'OAuth1a', 
    'clientKey'        => $publicKey,       
    'clientSecret'     => $secretKey,     
    'callback'         => $callback     
);


$auth = new ApiAuth();
$auth->newAuth($settings);

try {
    if ($auth->validateAccessToken()) {

        if ($auth->accessTokenUpdated()) {
            $accessTokenData = $auth->getAccessTokenData();
            echo $accessTokenData;
        }
    }
} catch (Exception $e) {
    // Do Error handling
}
```

If I just remove the try/catch, I end up with a blank page.

Thanks

**Comment by nickian** [comment]
Sorry, it looks like this was addressed in this thread: https://github.com/mautic/api-library/issues/58

updated this line:

`$auth->newAuth($settings);`

to this:

`$auth = $auth->newAuth($settings);`

It worked.

However, it should be noted that if you don't add `session_start();` toward the top of the file, you'll get other "undefined variable" errors. That should be in the example code.

**Comment by escopecz** [comment]
Please check https://github.com/mautic/api-library/pull/60 if it can be like that.
