### ISSUE TITLE
Problem after submitting form

### ISSUE THREAD

**Issue by michiellucas** [mautic/api-library#63]
Steps to reproduce error: Notice: Undefined index: state in Mautic\Auth\OAuth->validateAccessToken() (line 443 of Auth/OAuth.php).

- Created a new ApiAuth and succeeded in login. OK
- stored the access_token date
- asked form html structure and printed out in drupal website. OK
- Submitting form, values are saved in mautic. OK

- Redirect to website, Created a new ApiAuth with the access tokens and then i receive the error 
Notice: Undefined index: state in Mautic\Auth\OAuth->validateAccessToken() (line 443 of Auth/OAuth.php). 
I am not autorized anymore on mautic, receiving 403 on same call to the form.

When i remove the GETTERS from the url (?state=8d6767fb140182c6a6354f1510d66508&code=YjU1MzM2YjJiZTRmNjVmMTRmYjVjOGIyMjAzYzI1ODRjMDYzZWZhNjdiMDgxM2NkNjIzZDE3Nzc3MzhhYjA5OA) everything works back (access tokens are changed and the process starts again.)

the $_SESSION['oauth']['state'] is filled in the first time but after submitting the form the session oauth is emtpy

Mautic is latest version 2.1.1 and using composer package https://packagist.org/packages/mautic/api-library#dev-master

**Comment by escopecz** [comment]
I'm not quite sure what is the goal here. Could you please describe what are you trying to achieve? You can access forms without the API.

**Comment by michiellucas** [comment]
I want to embed forms in our drupal website, later on we want to use the api to track visitors + create leads.

**Comment by escopecz** [comment]
Ok, do you know you can [track users](https://mautic.org/docs/en/contacts/contact_monitoring.html) with the tracking script even with contact name, email and whatever information you want? [Embedding forms](https://mautic.org/docs/en/forms/manage_forms.html) can be also done without the API. There is also the [drupal-mautic plugin](https://github.com/mautic/mautic-drupal) available which will help you do all this and more. Is there any other reason why you need API?

**Comment by michiellucas** [comment]
We have custom forms build in in drupal, some information needs to be stored in drupal, some in mautic. Can you explain my error ?

**Comment by escopecz** [comment]
Ok, I can see you really want to use the API. I mention this last thing and then I leave you to it:

https://medium.com/@jan_linhart/the-simplest-way-how-to-submit-a-form-data-to-mautic-1454d3afd005#.52x8vao72

I don't understand why you are redirecting with the auth token or what is it?

**Comment by michiellucas** [comment]
the session is empty after the submit to mautic is complete ['state'] 

Do i need to start a new session first? 
When is the $_SESSION['oath']['state'] filled?


> I don't understand why you are redirecting with the auth token or what is it?

What do you mean?

**Comment by escopecz** [comment]
I mean

> When i remove the GETTERS from the url (?state=8d6767fb140182c6a6354f1510d66508&code=YjU1MzM2YjJiZTRmNjVmMTRmYjVjOGIyMjAzYzI1ODRjMDYzZWZhNjdiMDgxM2NkNjIzZDE3Nzc3MzhhYjA5OA) everything works back (access tokens are changed and the process starts again.)

I don't understand what URL you are talking about. Anyway, it's hard to help without the code. You can check how the PHP library works with session.

**Comment by michiellucas** [comment]
found the problem

**Comment by KamalMohamed** [comment]
@michiellucas,
 can you share with us your soultion plase

**Comment by shanecp** [comment]
Make sure you have `session_stat()` at the beginning of the script. And then re-start the authorization process.
