### ISSUE TITLE
Bug: OAuth1 API calls with complex data can fail with signature_invalid error

### ISSUE THREAD

**Issue by MarkLL** [mautic/api-library#75]
For OAuth1a API calls a Signature is calculated based on a normalized view of the data being sent in the request. see [RFC](https://tools.ietf.org/html/rfc5849#section-3.4).

If you attempt to send complex data the current algorithm for normalizing the SigningString has a bug which means your call can fail with a signature_invalid error.

**What is Complex data?**
Basically any array attached to a field whether it is a simple array or key/value array.

An example of a contact that will work.

```php
$contact = [
    'email' => 'joe@nowhere.con',
    'tags'   => ['aTag', 'zTag']
];
```
and one that will fail.
```php
$contact = [
    'email' => 'joe@nowhere.con',
    'tags'   => ['zTag', 'aTag']
];
```
Yes, just switching the order of the tags can break the compatibility of the API and the main Mautic app.

In essence, the problem exists because the API normalize function is recursive and begins by performing a `ksort()` on the parameters array. However as noted [here](https://oauth.net/core/1.0a/#anchor13) under section 9.1.1 (1) `If two or more parameters share the same name, they are sorted by their value`. Unfortunately recursively using `ksort()` breaks this compatibility.

For the techos' compare [normalizeParameters()](https://github.com/mautic/api-library/blob/master/lib/Auth/OAuth.php#L1000) used in the API to [normalizeRequestParameters()](https://github.com/willdurand/BazingaOAuthServerBundle/blob/master/Service/OAuthAbstractServerService.php#L301) used by Mautic. Also note that the Server version is not recursive and in general it looks like OAuth1a could not support 3 level deep arrays.

**Comment by escopecz** [comment]
Nice summary. Bugs like this are hard to find. Thanks for the fix!

**Comment by MarkLL** [comment]
Thanks @escopecz, yeah it took a bit of searching and testing to nail this sucker. I must say that OAuth1 is easier to test with that OAuth2 which is when I found the bug.  And to prove it was a OAuth1 issue, I created the BasicAuth provider so all in all, a better result for the API all round :)

**Comment by MarkLL** [comment]
Sadly it looks like the new additions to the API have broken OAuth1a. As mentioned above the server version of the normalizer does not cater with the deep array structure required to create some items via the api. The API unit test with https://github.com/mautic/mautic/pull/3244 installed now work for BasicAuth and OAuth2. Unfortunately, the following tests fail with OAuth1a. - mainly with `signature_invalid` errors, but it also cause a runtime. 
CampaignsTest, ContactFieldsTest, CompanyFieldTest, ContactsTest, EmailsTest, FormsTest, LeadsTest, PointTriggersTest, RolesTest and StatsTest are affected.
