### ISSUE TITLE
Basic Authorization

### ISSUE THREAD

**Issue by jozephbrasil** [mautic/api-library#77]
Hello guys. I am looking for examples about how to use basic authorization on API.

I have tried:

$settings = array(
    'baseUrl'          => '', // Base URL of the Mautic instance
    'version'          => 'basic',
    'clientKey'        => 'HTTP username',
    'clientSecret'     => 'HTTP password',
    'callback'         => '' // Redirect URI/Callback URI for this script
);

Anyone could help me about how to use it correctly?

**Comment by escopecz** [comment]
Check https://github.com/mautic/api-library/pull/73

**Comment by jozephbrasil** [comment]
Sorry. I am unable to see examples on #73.

**Comment by escopecz** [comment]
https://github.com/mautic/api-library/pull/73/files#diff-04c6e90faac2675aa89e2176d2eec7d8R103

**Comment by jozephbrasil** [comment]
@escopecz Why you don't apply (merge) PR #73 to master? Sorry, my difficult now is using GIT... How can I fetch #73 to my local api files?

**Comment by jozephbrasil** [comment]
OK! Done... If you need help about how to fetch PR, please take a look at: https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by escopecz** [comment]
@jozephbrasil the PR must be tested first and it was dependent on another PR which had to be merged first. If all the features from that PR works for you (or not), write a comment about it bellow that PR. It will speed up the merge.
