### ISSUE TITLE
Get Only Identified Contacts?

### ISSUE THREAD

**Issue by nickian** [mautic/api-library#80]
Is it possible to use the API to get only contacts that have been identified? Why does the API get every IP address that has visited a site by default? I can't imagine most people want this when getting contacts.

Also, what does this option mean? "publishedOnly - Only return currently published entities." 

And this? "minimal	- Return only array of entities without additional lists in it."

Nothing seems to change when I set these to "true."

Thanks

**Comment by escopecz** [comment]
Yes, use the `!is:anonymous` search command.

**Comment by nickian** [comment]
Awesome. Thank you! What do those other parameters do? What is an "unpublished" contact?

**Comment by fyopue** [comment]
Hi nickian.

API query :
orderBy=date_identified&orderByDir=desc

Try it!
