### ISSUE TITLE
Mautic - Requested URL not found - Fix

### ISSUE THREAD

**Issue by flexmarkets** [mautic/api-library#82]
Hey,

just wanted to report something. I think it should be added to the README file.

____________________

Here's what I found after trying everything, what is possible for a week:

Whenever I made API requests I got the "Requested URL not found" error all the time. 
It didn't matter what request has been done.

But all the time it was the same error (/api/contacts/new can be any other endpoint):

`error: {message: "Requested URL not found: /api/contacts/new", code: 404}`

____________________

Here's the super strange solution, that I have found:

In  | **Configuration -> System Settings -> Path to the cache directory** | you HAVO TO change the Path to the cache directory to a path **outside of the Mautic installation location**. 

____________________

_**Could someone explain me, why you have to do that?**_

Best regards,

FlexMarkets

**Comment by zspine** [comment]
@flexmarkets I had the same problem during php unit test, I just cleared the application cache and everything worked perfectly 'php app/console cache:clear'.

**Comment by escopecz** [comment]
@flexmarkets please let us know if clearing the cache worked for you.

**Comment by moltar** [comment]
Had the same problem. Clearing cache fixed it. Weird.

**Comment by moltar** [comment]
@escopecz any explanation why this happens? thanks!

**Comment by bazaglia** [comment]
Same here. `php app/console cache:clear` fixed. Perhaps the issue may be investigated.

**Comment by prouarch** [comment]
Thanks Flexmarkets for this 👍 
"In | Configuration -> System Settings -> Path to the cache directory | you HAVE TO change the Path to the cache directory to a path outside of the Mautic installation location."

I had troubles with WP Mautic Form Integration and it works now ! can't explain why :-(

**Comment by BrahimAfa** [comment]
n docker image instead of running
this:  php app/console cache:clear
this Fixed it for me : php bin/console cache:clear
thanx @zspine

**Comment by ramphy** [comment]
> n docker image instead of running this: php app/console cache:clear this Fixed it for me : php bin/console cache:clear thanx @zspine

Same here. `php bin/console cache:clear` fixed.
