### ISSUE TITLE
[Mautic 2.5.1] Points REST API

### ISSUE THREAD

**Issue by guillaumegarcia13** [mautic/api-library#87]
Although present in the Mautic REST API [documentation](https://developer.mautic.org/#add-points), when trying to use the Points endpoint, I get a 200 HTTP status but containing the following:
```
{
  "error": {
    "message": "Requested URL not found: /api/contacts/14637/points/plus/10",
    "code": 404
  }
}
```

Here is the request : https://mautic server/api/contacts/14637/points/plus/10
The contact is OK since I can get info using the endpoint : https://mautic server/api/contacts/14637

I am running : **Mautic 2.5.1**

**Comment by escopecz** [comment]
The documentation says it should be PATCH HTTP method, but in reality, it should be POST. Can you try it with POST?

**Comment by guillaumegarcia13** [comment]
POST is OK!

**Comment by escopecz** [comment]
Documentation fix: https://github.com/mautic/developer-documentation/pull/49
