### ISSUE TITLE
[Mautic 2.5.1] Create Segment 

### ISSUE THREAD

**Issue by guillaumegarcia13** [mautic/api-library#89]
Hi,

When trying to call the [endpoint for creating a Segment](https://developer.mautic.org/?php#create-segment), I got a 504 response.
Here is the JSON request:
```
{
    "isPublished": false,
    "name": "REST API Mautic test",
    "alias": "rest-api-mautic-test",
    "description": "test GGAR",
    "isGlobal": true
}
```
and I am calling this endpoint: https://< mautic server >/api/segments/new

From calling other endpoints with the same credentials, I'm pretty confident that the problem does not come from that.

**Comment by MarkLL** [comment]
Hmmm, it works ok for me... using your example I get...
```
{
  "list": {
    "isPublished": false,
    "dateAdded": "2017-02-07T23:42:41+11:00",
    "createdBy": 1,
    "createdByUser": "Admin User",
    "dateModified": null,
    "modifiedBy": null,
    "modifiedByUser": null,
    "id": 7,
    "name": "REST API Mautic test",
    "alias": "rest-api-mautic-test",
    "description": "test GGAR",
    "filters": [],
    "isGlobal": true
  }
}
```
I used Postman and Basic Authentication. I copied your example and set the header for `application/json` and POSTed it and hey presto it worked.

1. Make sure you set the `Content-Type` to `application/json` 
2. Use POST
3. Try clearing your Mautic cache

**Comment by guillaumegarcia13** [comment]
Seems related to my install and this other issue I created: https://github.com/mautic/mautic/issues/3269
I closed this one and will reopen if needed.
Thx.
