### ISSUE TITLE
Changes to AuthInterface break custom Auth Providers with Non Auth related changes

### ISSUE THREAD

**Issue by MarkLL** [mautic/api-library#91]
So I made a comment when this was proposed originally, but deleted because it may of be mis-construed.

However, I do not understand why the proposed changes were made! None of the new methods have *anything* to do with Authentication and the one method that is required and potentially *should* be added to the interface is missing. e.g. `validateAccessToken()`.

**Comment by HermanMonteiro** [comment]
Hello friend, I noticed that this validateAccessToken () method is also missing. Managed to solve?
