### ISSUE TITLE
Requested URL not found - Add Contact to a Stage

### ISSUE THREAD

**Issue by sillassoares** [mautic/api-library#95]
I'm trying to add a contact to a stage, but it keeps returning 404 error.

```
Array
(
    [error] => Array
        (
            [message] => Requested URL not found: /automacao/api/stages/1/contact/9/add
            [code] => 404
        )

)

```

The [documentation](https://developer.mautic.org/#add-contact-to-a-stage) says that the url should be

>  /stages/SEGMENT_ID/contact/add/CONTACT_ID

But i get the same error when i try to set the url on this way.
The version i'm using is 2.6.

**Comment by escopecz** [comment]
The `/automacao/` part shouldn't be there.

**Comment by sillassoares** [comment]
/automacao/ is part of my base url.

The odd thing is that all requests is working, except this one.

For example, i'm using 

> $stageApi->get($id);

before 

> $stageApi->addContact($contact, $stage);

**Comment by williamespindola** [comment]
@sillassoares @escopecz I have the same problem here, stageId and contactId params is inverted I fix this with mautic/developer-documentation#90

**Comment by escopecz** [comment]
@williamespindola thanks! That's correct
