### ISSUE TITLE
Rest Api to register contact events

### ISSUE THREAD

**Issue by Siva-93** [mautic/api-library#97]
Hi,

I'm very new to mautic. I want to know about rest api's of Mautic. So, I have a website. If user logs into my website mean, I'll create one account in Mautic. However, I've successfully created the account using rest API. If the same user logs into my site I want to register some events associated with that contact.

Is there any possibility to do with Mautic Rest Api's?

**Comment by escopecz** [comment]
There are 2 ways to do this:
1. Use a [fake form submission](https://medium.com/@jan_linhart/the-simplest-way-how-to-submit-a-form-data-to-mautic-1454d3afd005#.jyglub8w0) which can have its own form actions (standalone form) or use it in a campaign (campaign form). There is no need to use API for this.
2. Use the API to [create a contact](https://developer.mautic.org/#create-contact) and then [add her/him to a campaign](https://developer.mautic.org/#add-contact-to-a-campaign) (or [to a segment](https://developer.mautic.org/#add-contact-to-a-segment) which is source of a campaign) where she/he could to through the decisions and actions.
